Direwolf20-MC/BuildingGadgets

- src/main/java/com/direwolf20/buildinggadgets/blocks/ConstructionBlock.java
- src/main/java/com/direwolf20/buildinggadgets/entities/ConstructionBlockEntity.java
> Allow construction blocks to use neighboring block brightness.

- src/main/java/com/direwolf20/buildinggadgets/items/DestructionTool.java
- src/main/java/com/direwolf20/buildinggadgets/items/GenericPasteContainer.java
- src/main/java/com/direwolf20/buildinggadgets/tools/InventoryManipulation.java
This PR cleans up after the merge of #106.
> Cleanup of classes with recent merge conflicts.

- .gitignore
- update.json
This PR adds the update file missing from #106.
> Add update json file.

- src/main/java/com/direwolf20/buildinggadgets/tools/ToolRenders.java
> Optimize destruction overlay rendering.

- src/main/java/com/direwolf20/buildinggadgets/common/tools/InventoryManipulation.java
I could not find any negative effects of copying it... I don't know why it isn't included...
> Fix Trapdoor openState not being copied. (#164)

- src/main/java/com/direwolf20/buildinggadgets/common/entities/BlockBuildEntityRender.java
Logically this will stop it crashing the game if the error is thrown but it really shouldn't be happening. I'll be building out a version of the mod to let the person with the issue test if it is resolved. Don't pull in just yet 👍 
Sound fix: #165
> Resolves #165

- src/main/resources/assets/buildinggadgets/lang/en_us.lang
All other directions are capitalized, so this one should be as well.
> Fixed capitalization in en_us.lang

- src/main/java/com/direwolf20/buildinggadgets/common/blocks/templatemanager/TemplateManager.java
Fixes #201. Incredible that it's gone unnoticed for so long.
> Allow template manager block to drop stored items when broken.

- src/main/java/com/direwolf20/buildinggadgets/common/BuildingGadgets.java
> Add required Forge dependency (v14.23.3.2694).

- src/main/java/com/direwolf20/buildinggadgets/client/RemoteInventoryCache.java
- src/main/java/com/direwolf20/buildinggadgets/client/events/EventTooltip.java
- src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetCopyPaste.java
- src/main/java/com/direwolf20/buildinggadgets/common/network/PacketHandler.java
- src/main/java/com/direwolf20/buildinggadgets/common/network/PacketSetRemoteInventoryCache.java
- src/main/java/com/direwolf20/buildinggadgets/common/tools/GadgetUtils.java
- src/main/java/com/direwolf20/buildinggadgets/common/tools/InventoryManipulation.java
- src/main/java/com/direwolf20/buildinggadgets/common/tools/ToolRenders.java
- src/main/java/com/direwolf20/buildinggadgets/common/tools/UniqueItem.java
~~Dimension specification (I left some TODOs) and copy/paste tool support (can't set remote inventories for them) is not fully implemented, but I'll leave that to you Dire.~~
Everything is implemented now. Resolves #137.
> Finish implementing use and item count caching of remote inventories for gadgets.

- .gitignore
- CONTRIBUTION.md
Creates a CONTRIBUTION.md File which is included in the .gitignore to provide more information/guidelines of how to structure and style a PR.
> Add Contribution.md (Closes #227)

- CONTRIBUTION.md
I'm sure I've missed things but I feel this is required as otherwise we'll wind up making the same review comments continually 👍
> First draft of package guidelines.

- .gitignore
- EclipseCodeStyle.xml
- IntelliJIdeaCodeStyle.xml
- ide/idea/CodeStyle.xml
Just an enhancement for people who use IntelliJ IDEA to avoid making everybody setting the config themselves.
Unfortunately I don't use Eclipse anymore and don't have it installed, so I can't provide its code style config. If somebody has one they can also pull request them.
> Intellij IDEA code style config

- CONTRIBUTION.md
Add in some stuff that seems like common sense, but people may have some different opinion on them. Please point misleading and inappropriate entries out.
+ [x] Class structure (method/field order)
+ [x] Literal formats
+ [x] Inner class policy
+ [x] Import order
> Update contribution guide

- src/main/java/com/direwolf20/buildinggadgets/common/tools/InventoryManipulation.java
- src/main/java/com/direwolf20/buildinggadgets/common/tools/ToolRenders.java
Been a while so if someone could review, that would be great 👍 
Pos fix for #289 #280
> 1.12.x ToolRender class cleanup and Pos fix for #289 #280 maybe

- src/main/java/com/direwolf20/buildinggadgets/common/items/pastes/GenericPasteContainer.java
- src/main/java/com/direwolf20/buildinggadgets/common/registry/objects/BGBlocks.java
- src/main/java/com/direwolf20/buildinggadgets/common/registry/objects/BGItems.java
- src/main/java/com/direwolf20/buildinggadgets/common/util/tools/modes/BuildingMode.java
- src/main/java/com/direwolf20/buildinggadgets/common/util/tools/modes/ExchangingGridMode.java
> Fix bugs and formatting for 1.13.x branch

- src/api/java/com/direwolf20/buildinggadgets/api/building/Region.java
- src/main/java/com/direwolf20/buildinggadgets/common/util/blocks/RegionSnapshot.java
- src/main/java/com/direwolf20/buildinggadgets/common/util/exceptions/PaletteOverflowException.java
- src/main/java/com/direwolf20/buildinggadgets/common/util/helpers/LambdaHelper.java
This is the serialization method I came up with a "streak" system to compress the data. It is untested, and therefore was put here to be examined and improved by the others.
If I did something wrong or it won't work from the first place, please point that out.
When we accept it, it can be marked as ready and get merged; otherwise please leave as a draft.
> World snapshot and undo serialization algorithm

- src/main/java/com/direwolf20/buildinggadgets/client/gui/materiallist/MaterialListGUI.java
- src/main/java/com/direwolf20/buildinggadgets/client/gui/materiallist/ScrollingMaterialList.java
- src/main/java/com/direwolf20/buildinggadgets/client/gui/materiallist/SortingModes.java
- src/main/java/com/direwolf20/buildinggadgets/common/util/helpers/InventoryHelper.java
- src/main/java/com/direwolf20/buildinggadgets/common/util/lang/MaterialListTranslation.java
- src/main/resources/assets/buildinggadgets/lang/en_us.json
Added ability to copy material list as text into clipboard as addressed in #172.
> Copy material list as text into clipboard

- CONTRIBUTION.md
Included our primary goals from dire and cleaned up some wording as well as removing some parts that where a little too "teaching java".
Creating a PR for public spell check :D
> Updated contributing Guidelines

- README.md
Fixed some grammar and clarified some things
> Fix some grammar (possessive apostrophes)

- CONTRIBUTION.md
`An Supression should` -> `A Supression should`
Not sure about `Use immutablet types`, maybe its meant to be immutable<t>?
> Fix a typo in contribution guidelines

- src/main/java/com/direwolf20/buildinggadgets/common/packets/Packets.java
- src/main/java/com/direwolf20/buildinggadgets/common/packets/SetModePacket.java
- src/main/java/com/direwolf20/buildinggadgets/common/packets/SetRangePacket.java
- src/main/java/com/direwolf20/buildinggadgets/common/packets/UndoPacket.java
> Remove Handler classes

- src/main/java/com/direwolf20/buildinggadgets/common/construction/modes/CircleMode.java
- src/main/java/com/direwolf20/buildinggadgets/common/items/BuildingGadget.java
- src/main/java/com/direwolf20/buildinggadgets/common/items/DestructionGadget.java
- src/main/java/com/direwolf20/buildinggadgets/common/items/ExchangingGadget.java
Based on Mikey's circle code in: http://playcode.io/658452/
Had to do it slightly different because the circle has to be placed based on direction and thus in which direction to add the "x" and "y" has to be based on that.
Tried to optimize it as much as possible so no double block placements happen, but this is as far as I came (updated the playcode example with the same optimizations).
The better solution would maybe to use a Set instead of a list as the result of collect, then the deduplication is build in.
> Added hollow and filled circle mode.

- .github/workflows/gradle.yml
- build.gradle
- src/main/java/com/direwolf20/buildinggadgets/common/tileentities/ConstructionBlockTileEntity.java
- src/main/java/com/direwolf20/buildinggadgets/common/tileentities/EffectBlockTileEntity.java
- src/main/java/com/direwolf20/buildinggadgets/common/tileentities/TemplateManagerTileEntity.java
> Fixed tile entities not reading state correctly on read.

- src/main/java/com/direwolf20/buildinggadgets/client/ClientProxy.java
- src/main/java/com/direwolf20/buildinggadgets/client/renders/CopyPasteRender.java
- src/main/java/com/direwolf20/buildinggadgets/common/items/GadgetCopyPaste.java
The fix is done by registering the CopyPasteRender as an update listener to the clientside template provider.
> Fix the render not updating when the Template changes

- build.gradle
- src/main/resources/data/create/recipes/crushing/dense_construction_block.json
- src/main/resources/data/create/recipes/milling/dense_construction_block.json
- src/main/resources/data/create/recipes/washing/construction_paste.json
> Added create support for getting construction paste.
